language: scala

addons:
  ssh_known_hosts: maximskripnik.com:1505

script:
  - sbt
    scalafmtSbtCheck
    scalafmtCheckAll
    scalafixCheckAll
    clean
    coverage
    test
    coverageReport
    coveralls

before_deploy:
  - openssl aes-256-cbc -K $encrypted_233a0bc1cbfb_key -iv $encrypted_233a0bc1cbfb_iv
    -in .deploy/.key.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  script: scp -P 1505 openapi.yaml miknik@maximskripnik.com:openapi.yaml
  on:
    branch: develop

before_cache:
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.cache/coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt
